version: '3.3'
services:
    konata:
        build: ./midas-konata
        ports:
         - "3123:80"
        volumes:
         - ./midas-konata/conf.d/:/etc/nginx/conf.d
         - ./midas-konata/html/:/etc/nginx/html
        depends_on:
         - nagisa
         - misuzu
         - eru
    nagisa:
        build:
            context: ./midas-nagisa
            dockerfile: Dockerfile
        expose:
         - "8000"
        hostname: nagisa
        command: sh -c "elm make src/Main.elm --output=main.js && elm reactor"
        volumes:
         - ./midas-nagisa:/app
         - nagisa_node_modules:/app/node_modules
    misuzu:
        build: ./midas-misuzu
        expose:
         - "8080"
        hostname: misuzu
        command: sh -c "go build ./main.go && ./main"
        volumes:
         - ./midas-misuzu:/go/src/github.com/firedial/midas-misuzu
    eru:
        build: ./midas-eru
        expose:
         - "8080"
        hostname: eru
        command: "npm run start"
        volumes:
         - ./midas-eru:/app
         - eru_node_modules:/app/node_modules
    #     depends_on:
    #      - yui
    yui:
        build:
            context: ./midas-yui
            dockerfile: Dockerfile
        restart: always 
        env_file: ./midas-yui/.db_environment.env
        hostname: yui
        volumes:
         - db:/var/lib/mysql
    rikka:
        build: ./midas-rikka
        env_file: ./midas-rikka/.env
        volumes:
         - ./midas-rikka:/home/root
        privileged: true
        tty: true
volumes:
    eru_node_modules:
    nagisa_node_modules:
    db:


