version: '3.3'
services:
    konata:
        build: ./midas-konata
        ports:
         - "3123:80"
        volumes:
         - ./midas-konata/conf.d/:/etc/nginx/conf.d
        depends_on:
         - nagisa
         - misuzu
         - eru
    nagisa:
        build:
            context: ./midas-nagisa
            dockerfile: Dockerfile
        expose:
         - "8000"
        hostname: nagisa
    misuzu:
        build: ./midas-misuzu
        expose:
            - "8080"
        hostname: misuzu
    eru:
        build: ./midas-eru
        expose:
         - "8080"
        hostname: eru
        command: "npm run start"
        volumes:
         - ./midas-eru:/app
         - node_modules:/app/node_modules
    #     depends_on:
    #      - yui
    yui:
        build:
            context: ./midas-yui
            dockerfile: Dockerfile
        restart: always 
        volumes:
            - ./midas-yui/initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: pass
        hostname: yui
volumes:
    node_modules:


